# Generated by Django 4.2.11 on 2025-05-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assembly_id', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('geographic_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('assembly_id', models.CharField(max_length=50)),
                ('reference_name', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('reference_bases', models.CharField(max_length=1000)),
                ('alternate_bases', models.CharField(max_length=1000)),
                ('variant_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('molecular_consequence', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_significance', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_annotations', models.JSONField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='beacon_api.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantInDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(blank=True, max_length=10, null=True)),
                ('allele_frequency', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon_api.dataset')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon_api.individual')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon_api.variant')),
            ],
            options={
                'unique_together': {('variant', 'dataset', 'individual')},
            },
        ),
    ]
